language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: Tjf2K0T5q9XD3hCOgKjYazm0a7PSq5Op6koewmBW1v1FiGdMH7BF702evOssbZmYhpFMA3PZqbUkGrV1gVo2iSZSJIkaSI+8C9g7NMYLanDd84kK82oirH+OqxdJIxn8kOsMNRLnypzVzaHmHicOe1YVWNVJuex5QwW7t76QMAKoRD1lnl0J0IvkeKFAl/sX0QRRFyY+n8m3ALOaBtyVJ7GV6QR0Qzk1eAttxkohROA7ZMqvtaBWqkFExzXPufq5SlmI4b05KEeihd8FDbeZMFH/PLAVse5XFy6eDPlvGfKLBBItGGp7FAvI3jvF+RzLQf0OVBxmiIWn7WrRHPrgb15Iqu2zXypZe9GVVpFNZLy+QJMUZ6UnZ0dW2ctM/YjDIAJIVS1hAky03MtkhotdTaMZLWC6nDI5AeABwEJKZ3XAmrjeAvNDf4gMi7FdJcaZw7IZ/6tkjXZhdlEfTMRJnJV2vobXw+90OZQTQEECxtSwH8dux1yf88NYZdozQjjRAtVUcjwwLLo8iwAh+3emGbb+V85f+/KtD1mDi9cPcYn0YA7eH+2/ZiDRXYaA2pG+5cdsP35kvwH5jOJxYfbV5yBfO/MmlzqV+lmm0oCMW16wtPrQw6w0hNLfSGTTVTBix9/Z7nqqGw0EjfQUnm6AMM1vpcJehg5XdXRBVgIxDtY=
