language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: jhHNdrOLx/ViojllkIAJvWaS+kDnsMGEiVCnoHSxLx95uRq2FXHismyDOxqnFiFjflEEg45f4AYBuARGtXCdeLfvFcB/2ZTfmsC5TptBW+Dbj+sHgFMOCNlCs3YAl8+y1a/xIC53KO6XgqecHzuJI/zbflSbgUPce2i6k0wy0VgKkObppRox1Dc2+jkgBwp7oQOUXVpTTKfMdoM0+k/qhAn4GSYaXoFzZKDqTHI+JyFQfMNAJx5pJO6i/USSCH9KVIpMsKDY5Doy/41Ne2u0YN1AmNtROyKuKNGnWS4WupyXxxj43oKln57Wi+uSlRBirf0TM7j4UnVmpaR3GF8cEJy4D+hgFhSYxVlICP7JXzWJSXHZ55cqEEJDFlckK/0+OJILgufJPRyoxTDC08ZJ7v/9tEcKmptTlqZZfpjb0raiS7aL8iurg3t3yh2G2dNiiRpqncaYsl995Ex6Oya9Ba+MlNd3EItZPV7XCt3gvtEmHlPZjxuA0BlEXjG+p2XXkPSF2FUWYkmSB8e2T8xl4l1nvtLXVRro6ur6sVdv0WRbFqLler9LlX01rRm8ORlY92Lnc7Q2xupLYemqRQGqmVx0uW93n25mxkM+xQgAD5nbJ7+29M0TDqN9TY2HrgtUaYaW1Ay1iZzfXLtdOcF+PaW+5AkGCQRfZA1v+Umb4Uk=
