language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: CS28ri11hbIz/4hjvMSgiDeoC3hnKrLYBvdKFJKGDh9B7KXXkvYA6HCAVQVzXLwuQ6DqbCwDfNYXIgOncDLUxO44agqojiCPanqanvMjEmnJ+WOr/wHxNcUzyBfwshfCCUivYCWO2lE5Kh+M6b8yPKvlkBd2X0x21p58inFuvxuVDY30wovbNcyOThkgF4PUj+TYjf2a4r+xRVOFAajdVG4VccUtGjG+alc6BYe3le3ACKKF7Pqt/rvd8IOaA7qwXHVgpuvd0b2bbKWv32/opMtIY3C3DPrXZNP1l0QzvlvqMXI3SY0htMQHGPvoO3IGmwi/qg6TA3YE+P3CCw0kZAGvgXgFr65NRn0TYVNJHN8hGOhaMS6wMe3zHhEEOd5e1o8thll2488FoEXiirIiiaNXac0FPHqLpUWonlLORMOr3xpyuqdxezjNlTz10ZYnnapRHPF5PVpAoQB3/OiGK88a0sCMJVHw4YY8ch+dAmwKbLHmtfw9KZCVIrOwHaXEVqGqUraSbsVD636cTQYT6GUCmVkRjqo/fb9Hy7uPUs+6d72hPtcmmC/ihvMWDyNaa72T7VIFbqtpEjXVty0ETogPFpa6qouVwo3RptymILa3un2a1YW0nr0nLi+QgDkgQ0zLbvytFHCjOQtTRYw8X1mByKP5vAzz8+fjDHl02Z0=
